language: php

services:

php:
    - 8.4

sudo: false

before_script:
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - mkdir -p build/logs
    - php vendor/bin/phpcs src/ --standard=PSR12 -n
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
